version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: www.chashaotm.gq/simplep2p
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:4000"
      - "30000:30000"
    networks:
      - webnet
networks:
  webnet: